version: '3.8'

services:
  orchestrator:
    build: .
    container_name: ticktick-orchestrator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scheduler:
    build: .
    container_name: ticktick-scheduler
    command: ["node", "src/scheduler/daily-scheduler.js"]
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - orchestrator

networks:
  default:
    name: ticktick-network